backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "team"
    label: "Team Members"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "CNIC", name: "cnic", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Designation", name: "designation", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Registration Number", name: "regno", widget: "string" }
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
